# Generated by Django 4.0.5 on 2022-08-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0002_created_sessions_games_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='created_sessions',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magas.games_names'),
        ),
    ]
