# Generated by Django 4.0.5 on 2022-08-05 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magas', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_sessions',
            name='people_want_to_play',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
