# Generated by Django 4.0.5 on 2022-08-05 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magas', '0006_created_sessions_people_want_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='created_sessions',
            name='people_want_to_play',
        ),
        migrations.CreateModel(
            name='players_in_current_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
