# Generated by Django 4.0.5 on 2022-08-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0007_remove_created_sessions_people_want_to_play_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_sessions',
            name='players',
            field=models.ManyToManyField(to='magas.players_in_current_game'),
        ),
    ]
