# Generated by Django 4.0.5 on 2022-08-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0008_created_sessions_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='created_sessions',
            name='players',
        ),
    ]
