# Generated by Django 4.0.5 on 2022-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0009_remove_created_sessions_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players_in_current_game',
            name='player',
        ),
        migrations.AddField(
            model_name='players_in_current_game',
            name='player',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
