# Generated by Django 4.0.5 on 2022-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0010_remove_players_in_current_game_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players_in_current_game',
            name='approved_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
