# Generated by Django 4.0.5 on 2022-08-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magas', '0012_created_sessions_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='created_sessions',
            name='contacts',
            field=models.CharField(default='', max_length=40),
        ),
    ]
